server:
  port: 8020
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_max_it_max_it
    username: sididiop
    password: Toubakhayra

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

jwt:
  secret: maxit221SecretKeyForJWTTokenGeneration2024
  expiration: 86400000

cloudinary:
  cloud-name: dodmxir1f
  api-key: 865946363233566
  api-secret: DMID2P6WRxmVjduzmKeDxh72tsQ

gesclient:
  base-url: http://localhost:3000/api

appdaf:
  base-url: http://localhost:4000/api

transfer:
  external:
    fee-rate: 0.08

auth:
  code:
    expiration: 300000

logging:
  level:
    com.maxit.maxit221: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    title: API de Max It
    description: Cette API permet de gérer les transactions sur Max it.
    version: OPENAPI_3_1

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    title: Swagger UI - Gestion Max it